# Generated by Django 4.1.3 on 2022-11-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malile_khosh_kam', '0009_alter_malile_published_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_comment', models.CharField(max_length=200, verbose_name='عنوان نظر')),
                ('user_name', models.CharField(max_length=200, verbose_name='نام کاربر')),
                ('text_comment', models.TextField(verbose_name='متن نظر')),
                ('email_comment', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_khosh_kam', to='comment_khosh_kam.comment', verbose_name='والد')),
                ('user_ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.ipaddress', verbose_name='آی پی آدرس کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
