# Generated by Django 4.1.3 on 2022-11-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0012_alter_malile_published_time'),
        ('comment_khosh_kam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='malile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.malile', verbose_name='ملیله'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_ip_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.ipaddress', verbose_name='آی پی آدرس کاربر'),
        ),
    ]
