# Generated by Django 4.1.3 on 2022-11-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_khosh_kam', '0002_comment_malile_alter_comment_user_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject_comment',
        ),
    ]
