# Generated by Django 4.1.3 on 2022-11-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0014_alter_malile_published_time'),
        ('comment_khosh_kam', '0003_remove_comment_subject_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.ipaddress', verbose_name='آی پی آدرس کاربر'),
        ),
    ]
