# Generated by Django 4.1.3 on 2022-11-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_khosh_kam', '0004_alter_comment_user_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
