# Generated by Django 4.1.3 on 2023-01-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0023_alter_malile_published_time'),
        ('article_khosh_kam', '0006_alter_article_published_time'),
        ('comment_khosh_kam', '0005_remove_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='نام کاربر')),
                ('text_comment', models.TextField(verbose_name='متن نظر')),
                ('email_comment', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='article_khosh_kam.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_khosh_kam.articlecomment')),
                ('user_ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.ipaddress', verbose_name='آی پی آدرس کاربر')),
            ],
            options={
                'verbose_name': 'نظر مقاله',
                'verbose_name_plural': 'نظرات مقالات',
            },
        ),
    ]
