# Generated by Django 4.1.3 on 2023-01-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_khosh_kam', '0007_alter_articlecomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment_khosh_kam.articlecomment'),
        ),
    ]
