# Generated by Django 4.1.3 on 2023-02-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_khosh_kam', '0008_alter_articlecomment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
