# Generated by Django 4.1.3 on 2022-11-06 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=500, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='image_malile', verbose_name='تصویر')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('height', models.IntegerField(default=0, verbose_name='طول')),
                ('width', models.IntegerField(default=0, verbose_name='عرض')),
                ('weight', models.IntegerField(default=0, verbose_name='وزن')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('published_time', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 12, 21, 598039, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='اخرین به روز رسانی')),
                ('status', models.CharField(choices=[('d', ' پیش نویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('is_special', models.BooleanField(default=False, verbose_name='محصول ویژه')),
            ],
        ),
    ]
