# Generated by Django 4.1.3 on 2022-11-06 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 12, 54, 592927, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
