# Generated by Django 4.1.3 on 2022-11-06 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0003_alter_malile_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 15, 16, 121022, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='malile',
            name='title',
            field=models.CharField(default=None, max_length=500, verbose_name='عنوان'),
        ),
    ]
