# Generated by Django 4.1.3 on 2022-11-06 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0004_alter_malile_published_time_alter_malile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='آی پی آدرس')),
            ],
            options={
                'verbose_name': 'ی پی آدرس کاربران',
                'verbose_name_plural': 'آی پی آدرس کاربران',
            },
        ),
        migrations.AlterModelOptions(
            name='malile',
            options={'verbose_name': 'ملیله', 'verbose_name_plural': 'ملیله ها'},
        ),
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 21, 11, 155328, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='slider', max_length=200, verbose_name='عنوان')),
                ('active', models.BooleanField(default=False, verbose_name='اسلایدر فعال')),
                ('posts_slider', models.ManyToManyField(blank=True, null=True, related_name='slider_p', to='malile_khosh_kam.malile', verbose_name='پست های اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='MalileHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.ipaddress', verbose_name='آی پی آدرس')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.malile', verbose_name='مقاله')),
            ],
        ),
        migrations.CreateModel(
            name='CateGory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='عنوان دسته بندی در url')),
                ('status', models.BooleanField(default=True, verbose_name='این دسته بندی  نمایش داده شوند؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('image', models.ImageField(default='category/defualt.jpg', upload_to='category', verbose_name='تصویر دسته بندی')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='malile_khosh_kam.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
