# Generated by Django 4.1.3 on 2022-11-06 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0005_ipaddress_alter_malile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malilehit',
            options={'verbose_name': 'بازدید ملیله', 'verbose_name_plural': 'بازدید ملیله ها'},
        ),
        migrations.RemoveField(
            model_name='malilehit',
            name='post',
        ),
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 27, 31, 663092, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
