# Generated by Django 4.1.3 on 2022-11-06 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0006_alter_malilehit_options_remove_malilehit_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='malilehit',
            name='malile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.malile', verbose_name='ملیله'),
        ),
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 28, 23, 824076, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
