# Generated by Django 4.1.3 on 2022-11-06 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0007_malilehit_malile_alter_malile_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 37, 24, 647009, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
