# Generated by Django 4.1.3 on 2022-11-07 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0008_alter_malile_published_time_delete_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 11, 16, 51, 711818, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
