# Generated by Django 4.1.3 on 2022-11-07 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0009_alter_malile_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='malile',
            name='existing',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 14, 10, 24, 238011, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
