# Generated by Django 4.1.3 on 2022-11-07 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0010_malile_existing_alter_malile_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='malile',
            name='price',
            field=models.IntegerField(default=0, max_length=1000000, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 14, 24, 55, 154825, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
