# Generated by Django 4.1.3 on 2022-11-08 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0011_malile_price_alter_malile_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 19, 4, 39, 49521, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
