# Generated by Django 4.1.3 on 2022-11-11 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0014_alter_malile_published_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آی پی آدرس کاربر', 'verbose_name_plural': 'آی پی آدرس کاربران'},
        ),
        migrations.AddField(
            model_name='malile',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='malile_khosh_kam.ipaddress', verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 15, 5, 38, 11645, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
