# Generated by Django 4.1.3 on 2022-11-12 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0015_alter_ipaddress_options_malile_hits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 14, 44, 48, 247806, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
