# Generated by Django 4.1.3 on 2023-01-26 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0019_alter_malile_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='malile',
            name='category',
            field=models.ManyToManyField(related_name='malile_category', to='malile_khosh_kam.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='malile',
            name='hits',
            field=models.ManyToManyField(blank=True, null=True, related_name='hits', to='malile_khosh_kam.ipaddress', verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 17, 24, 40, 313857, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
        migrations.CreateModel(
            name='MalileGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='malile/{malile.title}/image_malile', verbose_name='تصویر')),
                ('malile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='malile_khosh_kam.malile', verbose_name='ملیله')),
            ],
            options={
                'verbose_name': 'گالری تصاویر ملیله',
                'verbose_name_plural': 'گالری تصاویر ملیله ها',
            },
        ),
    ]
