# Generated by Django 4.1.3 on 2023-01-27 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0022_alter_malile_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 21, 22, 49, 631594, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
