# Generated by Django 4.1.3 on 2023-01-28 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0024_alter_malile_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 19, 4, 55, 22148, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
