# Generated by Django 4.1.3 on 2023-02-08 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0025_alter_malile_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malile',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 13, 46, 26, 454294, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
