# Generated by Django 4.1.3 on 2023-01-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malile_khosh_kam', '0020_malile_category_alter_malile_hits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده')),
                ('payment_data', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=None, verbose_name='قیمت')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('malile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='malile_khosh_kam.malile', verbose_name=' محصول')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order_khosh_kam.order', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'جزییات محصول',
                'verbose_name_plural': 'جزییات محصول ها',
            },
        ),
    ]
