# Generated by Django 4.1.3 on 2023-01-26 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malile_khosh_kam', '0021_alter_malile_published_time'),
        ('article_khosh_kam', '0003_alter_article_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_category', to='malile_khosh_kam.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 17, 38, 7, 691248, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
