# Generated by Django 4.1.3 on 2023-01-27 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_khosh_kam', '0006_alter_article_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 21, 28, 20, 952081, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
